### ISSUE TITLE
meiForMJO.txt missing

### ISSUE THREAD

**Issue by MarkusKonk** [erikf28/FrazaEtAlASCMO#1]
Hi @erikf28 ,
the RMarkdown file includes meiForMJO.txt in line 2377 which is not included in this repo but your other one https://github.com/erikf28/FrazaElsnerASCMO. Just in case others do not know about that.

**Comment by MarkusKonk** [comment]
So I think the other repo is the actual and complete one. I found this one from the linkage in the corresponding publication.

**Comment by erikf28** [comment]
Thank you for bringing this to my attention. The files have been added to the FrazaEtAlASCMO repo, and the FrazaElsnerASCMO repo will be deleted shortly.
